// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzBSuA0YWW7zGQ-llNsMu_3SwE92VMli4',
    appId: '1:1025295981301:web:718aac64564544d02503bc',
    messagingSenderId: '1025295981301',
    projectId: 'forge-fit-app',
    authDomain: 'forge-fit-app.firebaseapp.com',
    storageBucket: 'forge-fit-app.firebasestorage.app',
    measurementId: 'G-XJ94F20LD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuJYlpts20aLwmz3dKnbpuJi9_IFuaHfA',
    appId: '1:1025295981301:android:fb4f3e9386a388132503bc',
    messagingSenderId: '1025295981301',
    projectId: 'forge-fit-app',
    storageBucket: 'forge-fit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQfwX2GJYuifqezG4adRhs82PwQRDMQsE',
    appId: '1:1025295981301:ios:eb99a99e4b7ceb382503bc',
    messagingSenderId: '1025295981301',
    projectId: 'forge-fit-app',
    storageBucket: 'forge-fit-app.firebasestorage.app',
    iosBundleId: 'com.example.forgeFitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQfwX2GJYuifqezG4adRhs82PwQRDMQsE',
    appId: '1:1025295981301:ios:eb99a99e4b7ceb382503bc',
    messagingSenderId: '1025295981301',
    projectId: 'forge-fit-app',
    storageBucket: 'forge-fit-app.firebasestorage.app',
    iosBundleId: 'com.example.forgeFitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzBSuA0YWW7zGQ-llNsMu_3SwE92VMli4',
    appId: '1:1025295981301:web:2894d1cfbe089e122503bc',
    messagingSenderId: '1025295981301',
    projectId: 'forge-fit-app',
    authDomain: 'forge-fit-app.firebaseapp.com',
    storageBucket: 'forge-fit-app.firebasestorage.app',
    measurementId: 'G-RFPKS4JJCL',
  );
}
